### ISSUE TITLE
Destructuring is non-intuitive

### ISSUE THREAD

**Issue by TimDaub** [ascribe/javascript#12]
Lately, I've been struggling with complying with [Section 5.2](https://github.com/ascribe/javascript#5.2) of the styleguide.

Essentially, when using Destructuring, what you're doing is providing Javascript with a path to locate certain values in an object.

Take this object as an example:

``` javascript
{
  name: 'Tim',
  profession: 'Dev',
  hobbies: {
      sports: {
         running: {
             motivation: 'high'
         },
         yoga: {
             motivation: 'zero'
         }
      }
   }
}
```

In our code, we want to define Tim's motivation for running as a local variable. We're using destructuring as a convenient way to do this.
The solution proposed in the styleguide would be:

``` javascript
const { hobbies: {
          sports: {
            running: {
              motivation
            }
          } } = tim;
```

However, when you think of destructuring just as a way of providing a path to an object and consider that we're using `{}`, intuitively it makes sense to format the destructuring blocks more like:

``` javascript
const {
  hobbies: {
    sports: {
      running: {
        motivation 
      }
    }      
  }
} = tim;
```

Which is why, I'd like to propose this as a improved solution to the styleguide.

**Comment by diminator** [comment]
:+1:

**Comment by vrde** [comment]
:+1: as well! Lol at the example :)

**Comment by sohkai** [comment]
:+1:
